// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace hyperionnet
{

public enum ImageType : byte
{
  NONE = 0,
  RawImage = 1,
};

public class ImageTypeUnion {
  public ImageType Type { get; set; }
  public object Value { get; set; }

  public ImageTypeUnion() {
    this.Type = ImageType.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public hyperionnet.RawImageT AsRawImage() { return this.As<hyperionnet.RawImageT>(); }

  public static int Pack(FlatBuffers.FlatBufferBuilder builder, ImageTypeUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case ImageType.RawImage: return hyperionnet.RawImage.Pack(builder, _o.AsRawImage()).Value;
    }
  }
}


}
