// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace hyperionnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Reply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Reply GetRootAsReply(ByteBuffer _bb) { return GetRootAsReply(_bb, new Reply()); }
  public static Reply GetRootAsReply(ByteBuffer _bb, Reply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Reply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Error { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(4); }
  public int Video { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public bool MutateVideo(int video) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, video); return true; } else { return false; } }
  public int Registered { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public bool MutateRegistered(int registered) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, registered); return true; } else { return false; } }

  public static Offset<hyperionnet.Reply> CreateReply(FlatBufferBuilder builder,
      StringOffset errorOffset = default(StringOffset),
      int video = -1,
      int registered = -1) {
    builder.StartTable(3);
    Reply.AddRegistered(builder, registered);
    Reply.AddVideo(builder, video);
    Reply.AddError(builder, errorOffset);
    return Reply.EndReply(builder);
  }

  public static void StartReply(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(0, errorOffset.Value, 0); }
  public static void AddVideo(FlatBufferBuilder builder, int video) { builder.AddInt(1, video, -1); }
  public static void AddRegistered(FlatBufferBuilder builder, int registered) { builder.AddInt(2, registered, -1); }
  public static Offset<hyperionnet.Reply> EndReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<hyperionnet.Reply>(o);
  }
  public static void FinishReplyBuffer(FlatBufferBuilder builder, Offset<hyperionnet.Reply> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedReplyBuffer(FlatBufferBuilder builder, Offset<hyperionnet.Reply> offset) { builder.FinishSizePrefixed(offset.Value); }
  public ReplyT UnPack() {
    var _o = new ReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ReplyT _o) {
    _o.Error = this.Error;
    _o.Video = this.Video;
    _o.Registered = this.Registered;
  }
  public static Offset<hyperionnet.Reply> Pack(FlatBufferBuilder builder, ReplyT _o) {
    if (_o == null) return default(Offset<hyperionnet.Reply>);
    var _error = _o.Error == null ? default(StringOffset) : builder.CreateString(_o.Error);
    return CreateReply(
      builder,
      _error,
      _o.Video,
      _o.Registered);
  }
};

public class ReplyT
{
  public string Error { get; set; }
  public int Video { get; set; }
  public int Registered { get; set; }

  public ReplyT() {
    this.Error = null;
    this.Video = -1;
    this.Registered = -1;
  }
  public static ReplyT DeserializeFromBinary(byte[] fbBuffer) {
    return Reply.GetRootAsReply(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    fbb.Finish(Reply.Pack(fbb, this).Value);
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
